#!/bin/bash

subdirs="arch/"
STOW=${STOW-stow}
STOW_CMD="$STOW -v -t $HOME"

git submodule init
git submodule update

for d in */; do
    if ! echo $subdirs | grep -q $d; then
        $STOW_CMD $d
    fi
done

# install machine-specific configs

if [[ -d arch && -e /etc/arch-release ]]; then
    (
        cd arch/
        for d in */; do
            $STOW_CMD $d
        done
    )
fi
