#!/bin/bash -x

bspc config border_width        2
bspc config window_gap          0

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      true
bspc config border_width        3
bspc config focused_border_color '#D85F00'
bspc config presel_feedback_color  '#D85F00'
bspc config remove_unplugged_monitors true

bspc rule -a '*:scratchpad' sticky=off state=floating center=on
bspc rule -a Gimp desktop=^8 follow=on state=floating
for browser in Chromium Firefox qutebrowser; do
    bspc rule -a $browser desktop=^2
done

# TODO: set up multiple monitors and autorandr.
bspc monitor -d {1..10}

polybar example &

urxvtc &

feh  --bg-scale '/usr/share/backgrounds/archlinux/wave.png' 
