#! /bin/sh

SCRIPT_DIR=$(dirname $0)

PANEL_HEIGHT=15
PANEL_FIFO=/tmp/panel-fifo
PANEL_FONT="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1"

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc subscribe report > "$PANEL_FIFO" &
echo -ne "T%s\n" | xargs -0 xtitle -sf > "$PANEL_FIFO" &
clock -sf 'S%a %b %d %H:%M' > "$PANEL_FIFO" &
#$HOME/src/pomo/pomo.sh status | sed -u 's/^/P/' > "$PANEL_FIFO" &

. $SCRIPT_DIR/panel_colors

$SCRIPT_DIR/panel_bar < "$PANEL_FIFO" | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" &

#wid=$(xdo id -a "$PANEL_WM_NAME")
#tries_left=20
#while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	#sleep 0.05
	#wid=$(xdo id -a "$PANEL_WM_NAME")
	#tries_left=$((tries_left - 1))
#done
#[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
