#! /bin/sh

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=15
PANEL_FONT_FAMILY="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1"
SCRIPT_DIR=$(dirname $0)
export PANEL_FIFO PANEL_HEIGHT PANEL_FONT_FAMILY SCRIPT_DIR

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %b %d %H:%M' > "$PANEL_FIFO" &
$HOME/src/pomo/pomo.sh status | sed -u 's/^/P/' > "$PANEL_FIFO" &

. $SCRIPT_DIR/panel_colors

cat "$PANEL_FIFO" | $SCRIPT_DIR/panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
